Import(['common_env', 'common_obj'])

checker_sources = ['checker.cpp', 'coro.cpp', 'ecs.cpp', 'gjk.cpp']

checker_env = common_env.Clone()
checker_env.UnitTest('checker', checker_sources + common_obj)
