Import(['env', 'common_sources'])

backend_sources = ['net.cpp', 'http.cpp', 'fs.cpp']

backend_env = env.Clone()
backend_env.Append(LIBS = ['ev', 'tls'])
backend_objs = backend_env.Object(backend_sources + common_sources)
server = backend_env.Program('server', backend_objs + ['main.cpp'])
backend = Install(backend_env['PREFIX'], server)

subdirs = ['unittest']
for subdir in subdirs:
    SConscript('%s/SConscript'%subdir, exports=['backend_env', 'backend_objs'])

Return('backend')
